忍无可忍无需再忍(指Issues内)
JLChnToZ/MCCustomSkinLoader pull request #238
Opened 2023-01-12 16:10 UTC by 8MiYile

看文件就知做啥的

2023-01-12 16:24 UTC, 8MiYile commented
https://github.com/8Mi-Tech/MCCustomSkinLoader/issues/1
好像有点小毛病哈哈

2023-01-12 16:27 UTC, xfl03 requested changes
感谢Pull Request，新版本CustomSkinLoader默认不会输出到latest.log，请在模板内带上CustomSkinLoader.log，以及加上Forge、Fabric的选项

2023-01-12 16:35 UTC, 8MiYile commented
已修复，请重新检查

2023-01-12 16:57 UTC, 8MiYile commented
修补部分细节

2023-01-12 17:07 UTC, 8MiYile commented
更改成只能通过模板生成issue

2023-01-13 00:37 UTC, ZekerZhayard commented on .github/ISSUE_TEMPLATE/report_bug.zh_CN.yml
> +       文件在文件夹 `. /.minecraft/crash-reports` 下里面找最近的报告生成时间
我觉得有相当一部分人的游戏路径并不是 .minecraft ，所以这方面描述位置的措辞可能还要改改

2023-01-13 04:46 UTC, 8MiYile commented on .github/ISSUE_TEMPLATE/report_bug.zh_CN.yml
> +       文件在文件夹 `. /.minecraft/crash-reports` 下里面找最近的报告生成时间
直接游戏目录/crash-report？

2023-01-13 04:55 UTC, ZekerZhayard commented on .github/ISSUE_TEMPLATE/report_bug.zh_CN.yml
> +       文件在文件夹 `. /.minecraft/crash-reports` 下里面找最近的报告生成时间
直接说「在游戏目录下的 `crash-reports` 文件夹下」，我相信能在 GitHub 开 issue 的人这部分应该还是能理解的

2023-01-13 04:59 UTC, 8MiYile commented on .github/ISSUE_TEMPLATE/report_bug.zh_CN.yml
> +       文件在文件夹 `. /.minecraft/crash-reports` 下里面找最近的报告生成时间
搞定

2023-01-13 05:33 UTC, ZekerZhayard commented on .github/ISSUE_TEMPLATE/report_bug.zh_CN.yml
> +       文件在文件夹 `. /.minecraft/crash-reports` 下里面找最近的报告生成时间
草，我的意思是：你把所有包含 `.minecraft` 目录的地方都改成游戏目录，包括中英文的

2023-01-13 05:49 UTC, 8MiYile commented on .github/ISSUE_TEMPLATE/report_bug.zh_CN.yml
> +       文件在文件夹 `. /.minecraft/crash-reports` 下里面找最近的报告生成时间
国外不都是正版用户嘛

2023-01-13 05:54 UTC, 8MiYile commented on .github/ISSUE_TEMPLATE/report_bug.zh_CN.yml
> +       文件在文件夹 `. /.minecraft/crash-reports` 下里面找最近的报告生成时间
难道你是说 为了同步？

2023-01-13 06:08 UTC, ZekerZhayard commented
@xfl03 我觉得没啥大问题了

2023-01-13 07:12 UTC, xfl03 approved these changes

2023-01-13 07:12 UTC, merged