add: common.yml: use matrix to multi-process upload file
JLChnToZ/MCCustomSkinLoader pull request #252
Opened 2023-04-20 10:25 UTC by 8MiYile

尝试加入多线程同时上传多个文件

2023-04-20 10:57 UTC, 8MiYile commented
make actions great again

2023-04-22 07:34 UTC, xfl03 requested changes

2023-04-22 07:34 UTC, xfl03 commented on .github/workflows/common.yml
> +        if: false
if还原一下

2023-04-22 07:34 UTC, xfl03 commented on .github/workflows/common.yml
>          name: Publish to CurseForge/Modrinth
这里应该是只发布到COS了

2023-04-22 07:37 UTC, 8MiYile commented on .github/workflows/common.yml
> +        if: false
稍等

2023-04-22 07:38 UTC, 8MiYile commented on .github/workflows/common.yml
>          name: Publish to CurseForge/Modrinth
这个地方 其实我有打算要废掉 你觉得要废掉吗

2023-04-22 07:44 UTC, xfl03 commented on .github/workflows/common.yml
>          name: Publish to CurseForge/Modrinth
你咋废掉 COS要上传的

2023-04-22 07:45 UTC, 8MiYile commented on .github/workflows/common.yml
>          name: Publish to CurseForge/Modrinth
那底下那块你不看看？

2023-04-22 08:12 UTC, xfl03 commented on .github/workflows/common.yml
>          name: Publish to CurseForge/Modrinth
COS发布为什么不一起多线程？

2023-04-22 08:15 UTC, 8MiYile commented on .github/workflows/common.yml
>          name: Publish to CurseForge/Modrinth
你得让我捋一捋那家伙要怎么多线程
因为Matrix矩阵里面的任务 都是单文件任务，然后你这cos。。。要上传啥我都不道呢。。要怎么拆分还是个问题捏（草）

2023-04-22 08:15 UTC, 8MiYile commented on .github/workflows/common.yml
>          name: Publish to CurseForge/Modrinth
你得让我捋一捋那家伙要怎么多线程
因为Matrix矩阵里面的任务 都是单文件任务，然后你这cos。。。要上传啥我都不道呢。。要怎么拆分还是个问题捏（草）

2023-04-23 12:14 UTC, xfl03 commented
GitHub Release也是发布渠道之一，为什么不能一起并行呢？

2023-04-23 12:18 UTC, 8MiYile commented
6

2023-04-23 12:44 UTC, xfl03 approved these changes

2023-05-12 03:14 UTC, merged