Fix crash when the URL of skull profiles is not valid.
JLChnToZ/MCCustomSkinLoader pull request #255
Opened 2023-05-02 06:25 UTC by ZekerZhayard

Fix #254

2023-05-02 07:13 UTC, XiaoPangxie732 commented
为什么不用orElseGet捏（

2023-05-07 05:53 UTC, xfl03 requested changes

2023-05-07 05:53 UTC, xfl03 commented on Common/src/main/java/customskinloader/fake/FakeMinecraftProfileTexture.java
> +        return Optional.ofNullable(this.info.hash).orElse(super.getHash());
`orElseGet` or conditional operator.

2023-05-07 08:38 UTC, xfl03 approved these changes

2023-05-07 08:38 UTC, merged