Add CSLPluginsLoader
JLChnToZ/MCCustomSkinLoader pull request #48
Opened 2019-03-05 15:38 UTC by ZekerZhayard

添加动态加载ProfileLoader的相关API;  

使用者需要把新的ProfileLoader相关jar包放在`.minecraft\CustomSkinLoader\Plugins`文件夹下;  
jar包的清单文件需要有`CustomSkinLoaderPlugin`属性，该属性的值应当为继承`customskinloader.plugins.ICustomSkinLoaderPlugin`接口的类的全名;

2019-03-05 16:40 UTC, xfl03 commented
主动去一个独立文件夹中加载是否感觉不太合适？
插件或许应该让Forge等ModLoader来加载并注册。

2019-03-06 08:02 UTC, ZekerZhayard commented
之前我的想法是类似于 [The 5zig Mod](https://www.5zig.net) 、 [Laby Mod](https://www.labymod.net) 、 [OldAnimationsMod](https://www.oldanimationsmod.net) 等可以不依赖Forge的模组那样加载插件的方式  
如果是要让ModLoader加载插件，我想用`Guava`的`EventBus`来控制，水平有限，只能想到这么多

2019-03-06 08:04 UTC, NekoCaffeine commented
直接用 spi 或者 弄个公有容器提供注册 不就好了

2019-03-06 09:49 UTC, yushijinhun commented
1. 应该使用ServiceLoader(SPI)。
2. CSL应该从非mods目录中加载JAR。理由如下：
    a. 开发CSL插件时不需要考虑版本兼容问题。
    b. 当CSL使用库文件挂载时，mods目录是没有的。
    c. 由于使用ServiceProvider，通过Mod来提供插件功能也是可以的。

2019-03-07 03:42 UTC, ZekerZhayard commented
尝试用ServiceLoader写了一个

2019-03-07 05:44 UTC, xfl03 commented
SPI设计比较合理了，请问这样的设计能从forge mod里加载插件吗？

2019-03-07 05:54 UTC, NekoCaffeine commented
> SPI设计比较合理了，请问这样的设计能从forge mod里加载插件吗？

1.13 之前 forge mod 的资源都可以从 lcl 获取到，所以应该可行。
至于 1.13 那个委托类加载器的行为得测一下，大概也行吧。

2019-03-07 09:39 UTC, yushijinhun requested changes

2019-03-07 09:39 UTC, yushijinhun commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
不需要单独写一个PluginClassLoader，直接URLClassLoader就行了。而且也不需要把父ClassLoader的urls加进去。

2019-03-07 09:39 UTC, yushijinhun commented on Common/source/customskinloader/plugin/PluginLoader.java
> +                    return fileName.endsWith(".jar") || fileName.endsWith(".zip");
为什么要检测.zip？

2019-03-07 09:39 UTC, yushijinhun commented on Common/source/customskinloader/plugin/PluginLoader.java
> +                    CustomSkinLoader.logger.warning("Could not load file: " + plugin.getName());
同时应当记录异常消息。

2019-03-07 11:20 UTC, xfl03 requested changes

2019-03-07 11:20 UTC, xfl03 commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
Java9开始默认不再使用URLClassLoader，或许不应该只支持Java8

2019-03-07 11:22 UTC, xfl03 commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
除了ClassLoader可能有待讨论，其他部分应该是没问题的了。

2019-03-07 16:12 UTC, ZekerZhayard commented
感谢各位大佬的指点

2019-03-08 04:32 UTC, NekoCaffeine commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
Java9 之后只是 APPClassLoader 不继承自 URLClassLoader，这无关 URLClassLoader 的使用

2019-03-08 04:38 UTC, NekoCaffeine commented on Common/source/customskinloader/plugin/PluginLoader.java
> +                } catch (MalformedURLException ignored) {}
这里不是说要无视啦

> 同时应当记录异常消息。

是让你 log 的时候把 Exception 也传一下

2019-03-08 04:39 UTC, NekoCaffeine requested changes

2019-03-08 04:39 UTC, NekoCaffeine commented on Common/source/customskinloader/plugin/PluginLoader.java
> +                } catch (MalformedURLException ignored) {}
这里不是说要无视啦

同时应当记录异常消息。

是让你 log 的时候把 Exception 也传一下

2019-03-08 05:33 UTC, xfl03 commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
@NekoCaffeine `(URLClassLoader) PluginLoader.class.getClassLoader()`
这样会出Cast错误的。

2019-03-08 05:34 UTC, xfl03 approved these changes

2019-03-08 05:34 UTC, NekoCaffeine commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
lcl 是 URLClassLoader， ml 的也是

2019-03-08 05:35 UTC, NekoCaffeine commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
你是指原版挂载？倒是个问题

2019-03-08 05:38 UTC, NekoCaffeine commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
反正 92446c1399ec96d331d25f6a35b45bd0168f1407 里挺好的，就是该 log 一下异常

2019-03-08 05:38 UTC, merged

2019-03-08 05:40 UTC, xfl03 commented on Common/source/customskinloader/plugin/PluginLoader.java
> +    private static PluginClassLoader pcl = new PluginClassLoader(((URLClassLoader) PluginLoader.class.getClassLoader()).getURLs(), PluginLoader.class.getClassLoader());
log我自行解决吧 问题不大

2019-03-08 09:47 UTC, yushijinhun commented on Common/source/customskinloader/plugin/PluginLoader.java
> +                } catch (MalformedURLException ignored) {}
@xfl03 请把这里改掉。