Allow users to customize the size of thread pools.
JLChnToZ/MCCustomSkinLoader pull request #86
Opened 2020-04-09 06:52 UTC by ZekerZhayard

允许用户自定义线程池大小。
Minecraft 1.15 之后版本，皮肤加载的过程被放到了一个公共的线程池中，这个线程池的大小和CPU核心数有关，而不是再像1.14以前那样单线程加载皮肤。那么我觉得给CSL添加一个自定义线程池大小也是非常有必要的。

2020-04-09 09:32 UTC, xfl03 requested changes

2020-04-09 09:32 UTC, xfl03 commented on Common/source/customskinloader/CustomSkinLoader.java
> +    private static final ThreadPoolExecutor threadPool = new ThreadPoolExecutor(config.threadPoolSize, config.threadPoolSize, 1L, TimeUnit.MINUTES, new LinkedBlockingQueue<>());
1.corePoolSize不一定要和maximumPoolSize一致，前者是不会被回收的线程，后者是最多可以同时执行的线程
2.必须指定队列长度，建议指定拒绝策略，以免[OOM](https://zhuanlan.zhihu.com/p/32867181)

2020-04-09 09:37 UTC, xfl03 requested changes

2020-04-09 09:37 UTC, xfl03 commented on Common/source/customskinloader/config/Config.java
> +    public int threadPoolSize = 1;
默认线程数为1的话，是否会导致头颅加载过于缓慢以及请求堆积呢？

2020-04-09 10:05 UTC, ZekerZhayard commented on Common/source/customskinloader/config/Config.java
> +    public int threadPoolSize = 1;
对于原版1.14以前以及原先的CSL而言，加载皮肤的[线程池](https://github.com/xfl03/MCCustomSkinLoader/blob/a714670b9abd18d0320bf97fe92cbc779b70329c/Common/source/customskinloader/fake/FakeSkinManager.java#L33)相当于单线程

2020-04-09 10:08 UTC, ZekerZhayard commented on Common/source/customskinloader/CustomSkinLoader.java
> +    private static final ThreadPoolExecutor threadPool = new ThreadPoolExecutor(config.threadPoolSize, config.threadPoolSize, 1L, TimeUnit.MINUTES, new LinkedBlockingQueue<>());
我觉得你给的参考的OOM的原因是开启的线程过多，而不是队列内元素过多

2020-06-28 16:57 UTC, xfl03 approved these changes

2020-06-28 16:57 UTC, merged